### ISSUE TITLE
Ending broken on itch.io

### ISSUE THREAD

**Issue by rocketnia** [Rumpelcita/evitasempai#1]
Hi, when I originally played this game [at itch.io](https://rumpelcita.itch.io/evitasempai), it suddenly turned into a page that said "302 Found":

![screen shot 2016-04-06 at 1 48 07 pm](https://cloud.githubusercontent.com/assets/155658/14332358/058a94e0-fbfe-11e5-9cd0-7bfe7709a6f1.png)

To see if I was missing anything, I replayed [on GitHub Pages](http://rumpelcita.github.io/evitasempai/) and got to the same point, and it refreshed to the title screen. I'm guessing that was the desired behavior. Maybe it would be better if the Spring Thing page linked to that URL instead.

**Comment by Rumpelcita** [comment]
Yes, that's the desired behavior. I guess it has to do with the iframe that itch.io uses.

Thanks for the heads up.

I did a quick fix until the guys at the Spring Thing update the url.

**Comment by Rumpelcita** [comment]
The url has been updated.

Thanks a ton!

**Comment by rocketnia** [comment]
Glad this helped! This story was pretty moving, so I'm glad other readers will get a more seamless experience out of it now.
